# (c) Andrew Wei

version: 2
jobs:
  build:
    working_directory: ~/meno
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - deploy:
          name: Publish to NPM
          command: |
            if [[ $(git describe --tags) =~ ^v[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_AUTH" >> ~/.npmrc
              npm publish
              echo "Successfully published to NPM"
            else
              echo "Skipping publish because this is not a release"
            fi
      - deploy:
          name: Publish demo to GitHub pages
          command: |
            if [[ $(git describe --tags) =~ ^v[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$ ]]; then
              if [ `git branch | grep gh-pages` ]
              then
                git branch -D gh-pages
              fi
              git checkout -b gh-pages
              npm run demo:build

              # Move generated demo to root and delete everything else.
              find . -maxdepth 1 ! -name '.' ! -name '..' ! -name 'demo' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;
              mv demo/public/* .
              rm -R demo/

              # Push to gh-pages.
              ORIGIN_URL=`git config --get remote.origin.url`

              git config user.name "$GITHUB_USERNAME"
              git config user.email "$GITHUB_EMAIL"
              git add -fA
              git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
              git push -f $ORIGIN_URL gh-pages

              echo "Successfully published demo to GitHub pages"
            else
              echo "Skipping publish because this is not a release"
            fi